#!/usr/bin/env bash
# This bash script transfers a file from our client to a server
if [ "$#" -lt 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

fileName="$1"
serverIP="$2"
username="$3"
pathToSSHkey="$4"

scp -o StrictHostKeyChecking=no -i "$pathToSSHkey" "$fileName" "$username"@"$serverIP":~/