#!/usr/bin/env bash
# This bash script installs nginx on my remote server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!\n' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart