#!/usr/bin/env bash
# This script configures my Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo rm -f /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/index.nginx-debian.html
# sudo echo '301 Moved Permanently' | sudo tee /var/www/html/index.nginx-debian.html
sudo sh -c "echo '301 Moved Permanently' | tee /var/www/html/index.nginx-debian.html && exit 301"
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start