#!/usr/bin/env bash
# This bash script installs and configures an HAproxy on my lb-01 server

sudo apt update
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
sudo printf "\nlisten www\n\tbind :80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?status\n\tbalance roundrobin\n\tserver 530596-web-01 35.153.255.15:80 check\n\tserver 530596-web-02 100.27.4.210 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy restart
