#!/usr/bin/env bash
# This bash script fixes the issue that is keeping
# our Ubuntu container's Nginx installation from
# from listening on port 80.

# BTW, my nginx server was already configured to 
# listen on port 80 so this script basically did nothing.

sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -1 nginx
