#!/usr/bin/env bash
# This script displays "To infinty and beyond" indefintely.
# But in between each iteration of the loop, a sleep 2 command is going to be added.

while true;
do
	echo "To infinity and beyond"
	sleep 2
done
