#!/usr/bin/env bash
# This script displays the numbers from 1 to 100.
# Only Condition: It must be fizz buzzed.
# And by now, we should all know what the fizz buzz thing is.
i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
        then
                echo "Buzz"
	else
		echo "$i"
	fi
	((i++))

done
