#!/usr/bin/env bash
# This script displays "Best School" 10 times using the while loop
# Only addtional condition: "Hi" must be printed in the 9th iteration
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))

done
