#!/usr/bin/env bash
# This bash script displays the content of the current directory
# In a list format where only the part of the name after
# the first dash is displayed

for file in *;
do
	if [ -f "$file" ];
	then
		anita=$(echo "$file" | cut -d'-' -f2-)
		echo "$anita"
	fi
done
