#!/usr/bin/env bash
# This script give you information about the school file.
# I dont want to list all the conditions here.
# Have a look for yourself.
# It is pretty straight forward.

filePath="school"
if [ -e "$filePath" ];
then
	echo "school file exists"
	
	if [ -s "$filePath" ];
	then
        	echo "school file is not empty"
    	else
        	echo "school file is empty"
	fi

	if [ -f "$filePath" ];
        then
                echo "school is a regular file"
        else
                :
        fi
else
    echo "school file does not exist"
fi
