#!/usr/bin/env bash
# This script creates an RSA key pair with the following specifications:
# Name of the created private key should be school
# Number of bits in the created key should be 4096
# And the created key must be protected by the passphrase betty

ssh-keygen -b 4096 -f school -N betty
